routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Category;
use App\Course;
use App\Filter;
use App\User;
use App\Training;
use App\Comment;
use App\Organization;


Route::get('/', function () {


	$categories = Category::all();
	$courses = Course::all();
	$comments = Comment::all();
	$filters = Filter::all();
	//$trainings = Training::all();
	$trainings = Training::orderby('start_date', 'asc')->get();
	$organizations = Organization::all();
	$users = User::all();

	//Put homepage path to session, to be accessed from logincontroller
	session(['path' => '/']);

    return view('welcome')->with('categories', $categories)
    					  ->with('courses', $courses)
    					  ->with('filters', $filters)
    					  ->with('comments', $comments)
    					  ->with('trainings', $trainings)
    					  ->with('organizations', $organizations)
    					  ->with('users', $users);
})->name('/');

Route::get('/events/results', function(){

	$events = Training::where('title', 'like', '%' . request('query') . '%');
	$trainings = Training::all();

	return view('events.results')->with('events', $events)
						  		->with('title', 'Search results : ' . request('query'))
								  ->with('query', request('query'))
								  ->with('trainings', $trainings);

});

Route::post('/events/materials', 'EventController@materials');

Route::get('/test', function() {


	return view('test');


});



Auth::routes();

Route::post('/home', 'HomeController@store')->name('home.store');



Route::get('contact', 'EventController@contact')->name('contact'); //Consider a dedicated controller here

Route::resource('events', 'EventController');
Route::resource('courses', 'CurriculumController');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/upcoming', 'HomeController@upcoming')->name('upcoming');
Route::get('/setting', 'HomeController@setting')->name('setting');



Route::post('/setting', 'HomeController@updateSetting')->name('update-setting');

Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay');

Route::get('/purchase', function(){



	return view('purchase');

});


Route::post('delegates/add', 'DelegateController@add');

Route::post('delegates/persist', 'DelegateController@persist');

Route::post('delegates/proof', 'DelegateController@payment_proof')->name('delegates.proof');

Route::post('delegates/narration', 'DelegateController@narration')->name('narration.proof');

Route::get('delegates/transactions/update', 'DelegateController@edit_transactions');

Route::post('delegates/transactions/update', 'DelegateController@update_transactions')->name('transactions.update');

Route::post('upload', 'HomeController@upload');

Route::post('/purchase', 'DelegateController@purchase')->name('purchase');

//note to self: consider putting path session here as well just like in home

Route::post('delegates/create', 'DelegateController@create');

Route::resource('delegates', 'DelegateController');

Route::get('/resources', 'ListResourcesController@index');


Route::prefix('admin')->middleware('role:superadministrator|administrator')->group(function () {

	Route::get('/', 'AdminController@index');

	Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');

	Route::resource('categories', 'CategoryController');

	Route::resource('courses', 'CourseController');

	Route::resource('filters', 'FilterController');

	Route::resource('trainings', 'TrainingController');

	Route::resource('instructors', 'InstructorController');

	Route::resource('organizations', 'OrganizationController');

	Route::resource('comments', 'CommentController');

	Route::resource('users', 'UserController');

    Route::resource('materials', 'MaterialController');

    Route::resource('resources', 'ResourceController');

	Route::resource('logos', 'LogoController');

	Route::resource('transactions', 'TransactionController');

	Route::resource('/permissions', 'PermissionController', ['except' => 'destroy']);
    Route::resource('/roles', 'RoleController', ['except' => 'destroy']);

});

resources/views/_admin.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Area | Dashboard</title>
    <!-- Bootstrap core CSS -->
    <!-- <link href="assets/css/bootstrap.css" rel="stylesheet"> Glypicon not working-->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="/assets/css/admin/style.css" rel="stylesheet">
    <link href="/assets/css/admin/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <link href="/assets/css/toastr.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">

    <script src="http://cdn.ckeditor.com/4.6.1/standard/ckeditor.js"></script>

    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
    <script>
      tinymce.init({
      selector:'textarea',
      plugins: "lists"
      });
    </script>
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Admin</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">

            <li><a href="{{route('users.index')}}">Users</a></li>
            <li><a href="{{route('organizations.index')}}">Organizations</a></li>
            <li><a href="{{route('trainings.index')}}">Training</a></li>
            <li><a href="{{route('categories.index')}}">Categories</a></li>
            <li><a href="{{route('courses.index')}}">Courses</a></li>
            <li><a href="{{route('materials.index')}}">Materials</a></li>
            <li><a href="{{route('comments.index')}}">Comments</a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Welcome {{ Auth::user()->first_name }} </a></li>
            <li><a href="{{ route('logout') }}" class="cs-logout" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">Logout</a></li>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
            </form>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <header id="header">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Wizer Consulting <small>Dashboard</small></h1>
          </div>

        </div>
      </div>
    </header>


    <section id="main">
      <div class="container" id="app">
        @include('_errors')
        @include('flash')
        <div class="row">
          <div class="col-md-3">
            <div class="list-group">
              <a href="index.html" class="list-group-item active main-color-bg">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Dashboard
              </a>
              <a href="{{route('users.index')}}" class="list-group-item"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Users <span class="badge">{{count($users)}}</span></a>
              <a href="{{route('organizations.index')}}" class="list-group-item"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> Organizations <span class="badge">{{count($organizations)}}</span></a>
              <a href="{{route('trainings.index')}}" class="list-group-item"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> Trainings <span class="badge">{{count($trainings)}}</span></a>
              <a href="{{route('instructors.index')}}" class="list-group-item"><span class="glyphicon glyphicon-education" aria-hidden="true"></span> Instructors <span class="badge">{{count($instructors)}}</span></a>
              <a href="{{route('categories.index')}}" class="list-group-item"><span class="glyphicon glyphicon-sort-by-attributes" aria-hidden="true"></span> Categories <span class="badge">{{count($categories)}}</span></a>
              <a href="{{route('courses.index')}}" class="list-group-item"><span class="glyphicon glyphicon-education" aria-hidden="true"></span> Courses <span class="badge">{{count($courses)}}</span></a>
              <a href="{{route('materials.index')}}" class="list-group-item"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Materials <span class="badge">{{count($materials)}}</span></a>
              <a href="{{route('resources.index')}}" class="list-group-item"><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Resources <span class="badge">{{count($resources)}}</span></a>
              <a href="{{route('comments.index')}}" class="list-group-item"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Comments <span class="badge">{{count($comments)}}</span></a>
              <a href="{{route('logos.index')}}" class="list-group-item"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span> Logos <span class="badge">{{count($logos)}}</span></a>

              <a href="{{route('transactions.index')}}" class="list-group-item"><span class="glyphicon glyphicon-euro" aria-hidden="true"></span> Transactions <span class="badge">{{count($transactions)}}</span></a>
              <a href="{{route('permissions.index')}}" class="list-group-item"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span> Permissions</a>
              <a href="{{route('roles.index')}}" class="list-group-item"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span> Roles</a>


            </div>


          </div>
          @yield('content')
        </div>
      </div>
    </section>

    <footer id="footer" style=" bottom: 0; width: 100%;">
      <p>© {{ Carbon\Carbon::now()->year }} Wizer Consulting All Rights Reserved.</p>
    </footer>

    <!-- Modals -->

    <!-- Add Page -->
    <div class="modal fade" id="addPage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <form>
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Add Page</h4>
            </div>
            <div class="modal-body">
              <div class="form-group">
                <label>Page Title</label>
                <input type="text" class="form-control" placeholder="Page Title">
              </div>
              <div class="form-group">
                <label>Page Body</label>
                <textarea name="editor1" class="form-control" placeholder="Page Body"></textarea>
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Published
                </label>
              </div>
              <div class="form-group">
                <label>Meta Tags</label>
                <input type="text" class="form-control" placeholder="Add Some Tags...">
              </div>
              <div class="form-group">
                <label>Meta Description</label>
                <input type="text" class="form-control" placeholder="Add Meta Description...">
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
          </form>
        </div>
      </div>
    </div>





    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <script src="/assets/scripts/admin/moment-with-locales.min.js"></script>
    <script src="/assets/scripts/admin/bootstrap.min.js"></script>
    <script src="{{asset('js/app.js')}}"></script>
    <script src="/assets/scripts/admin/bootstrap-datetimepicker.min.js"></script>



    <script>
      CKEDITOR.replace( 'editor1' );

      $('#datetimepicker1').datetimepicker({format:'YYYY-MM-DD HH:mm:ss'});
      $('#datetimepicker2').datetimepicker({format:'YYYY-MM-DD HH:mm:ss'});
    </script>

    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>

    <script>
      $(document).ready( function () {
      $('#table').DataTable();
      } );
    </script>



  </body>
</html>

resources/views/_errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/_footer.blade.php
{{--  Footer start  --}}
<footer id="footer"> 


    <div class="cs-copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="copyright-text">
                        <p>© {{ Carbon\Carbon::now()->year }} Wizer Consulting All Rights Reserved.</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="cs-social-media">
                        <ul>
                            <li><a href="index.html#"><i class="icon-facebook2"></i></a></li>
                            <li><a href="index.html#"><i class="icon-twitter2"></i></a></li>
                            <li><a href="index.html#"><i class="icon-instagram2"></i></a></li>
                            <li><a href="index.html#"><i class="icon-youtube3"></i></a></li>
                            <li><a href="index.html#"><i class="icon-linkedin22"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>


</footer>
{{--  Footer end  --}}

resources/views/_main.blade.php
@include('_header')

            
    @yield('content')
    {{--  @include('flash')  --}}

    
    {{--  Footer start  --}}
    <!-- <footer id="footer"> 


        <div class="cs-copyright">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class="copyright-text">
                            <p>© 2018 Wizer Consulting All Rights Reserved.</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class="cs-social-media">
                            <ul>
                                <li><a href="index.html#"><i class="icon-facebook2"></i></a></li>
                                <li><a href="index.html#"><i class="icon-twitter2"></i></a></li>
                                <li><a href="index.html#"><i class="icon-instagram2"></i></a></li>
                                <li><a href="index.html#"><i class="icon-youtube3"></i></a></li>
                                <li><a href="index.html#"><i class="icon-linkedin22"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </footer> -->
    @include('_footer')
    {{--  Footer end  --}}
    </div>

    <script src="/assets/scripts/responsive.menu.js"></script> <!-- Slick Nav js --> 
    <script src="/assets/scripts/chosen.select.js"></script> <!-- Chosen js --> 
    <script src="/assets/scripts/slick.js"></script> <!-- Slick Slider js --> 
    <script src="/assets/scripts/jquery.mCustomScrollbar.concat.min.js"></script> 
    <script src="/assets/scripts/jquery.mobile-menu.min.js"></script><!-- Side Menu js --> 
    <script src="/assets/scripts/counter.js"></script><!-- Counter js --> 

    <!-- Put all Functions in functions.js --> 
    <script src="/assets/scripts/functions.js"></script>

    <!--isotope here...-->
    <script src="/assets/scripts/isotope.pkgd.min.js"></script>

    <script src="/assets/scripts/wizer_training-2.js"></script>

    <script src="/assets/scripts/owl.carousel.min.js"></script>

    <script>
        $('.owl-carousel').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        autoplay:true,
        autoplayTimeout:3000,
    autoplayHoverPause:true,
        responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
        }
        })
    </script>

    <!-- <script>
        jQuery(document).ready(function(){
        jQuery('#login-modal').click(function(e){
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                }
            });
            jQuery.ajax({
                url: "{{ url('/login') }}",
                method: 'post',
                data: {
                    email: jQuery('#email').val(),
                    password: jQuery('#password').val(),
                    
                },
                success: function(result){
                    if(result.code == 0){
                        window.location.href = "/home"
                    }else{

                        //console.log(result.code);
                        alert('Incorrect email and/or password');
                    }
                }});
            });
        });
    </script> -->

    <script type="text/javascript">
        const app3 = new Vue({
        el: '#login-modal',


        data: {
            form: {
                email : '',
                password : '',
            },
            allerrors: [],
            success : false,    
        },
        methods : {
            onSubmit() {


                dataform = new FormData();
                dataform.append('email', this.form.email);
                dataform.append('password', this.form.password);
                


                axios.post('/login', dataform).then( response => {
                   
                    this.allerrors = [];
                    this.form.email = '';
                    this.form.password = '';
                    this.success = true;
                    window.location.href = "/"
                } ).catch((error) => {
                         this.allerrors = error.response.data.errors;
                         this.success = false;
                    });
            }
        }
    });
    </script>

   

    <!-- <script src="{{asset('js/app.js')}}"></script> -->
    <script>
        $('div.alert').not('.alert-important').delay(5000).fadeOut(350);
    </script>
</body>
</html>

resources/views/_profile.blade.php
@extends('_main')



<!-- Sub Header Start -->  
<div class="page-section" style="background:#ebebeb; padding:50px 0 35px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="cs-page-title">
                    <h1>{{Auth::user()->first_name}}</h1>
                    <p style="color:#aaa;">650+ video-based courses and short courses to help you develop creative and technical skills.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Sub Header End --> 

<!-- Main Start -->
<div class="main-section">
    <div class="page-section">
        <div class="container">
            <div class="row">
                <div class="page-sidebar col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="cs-user-sidebar">
                        <div class="cs-profile-pic">
                            <div class="profile-pic">
                                <div class="cs-media">
                                    <figure> <img src="{{ asset($user->avatar) }}" alt="" style="60px" height="60px" style="border-radius: 50%"> </figure>
                                </div>
                            </div>
                            <form action="{{route('home.store')}}" enctype="multipart/form-data" method="post">
                              @csrf
                              <div class="cs-browse-holder"> <em>My Profile Photo</em>
                                <span class="file-input btn-file"> Update Avatar
                                  <input type="file" name="avatar">

                                </span><br><br>
                                <button type="submit" class="btn btn-file btn-sm">Save</button>

                              </div>

                            </form>
                        </div>
                        <div class="cs-usser-account-list">
                            <ul>
                                <!-- <li><a href="instructor-detail.html"><i class="icon-user3 cs-color"></i>About me</a></li> -->
                                <li class="active"><a href="instructor-courses.html"><i class="icon-graduation-cap cs-color"></i>My Courses</a></li>
                                <li><a href="instructor-statements.html"><i class="icon-file-text2 cs-color"></i>Statement</a></li>
                                <li><a href="instructor-account-setting.html"><i class="icon-gear cs-color"></i>Profile Setting</a></li>
                            </ul>
                            <a href="{{ route('logout') }}" class="cs-logout" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><i class="icon-log-out cs-color"></i>Logout</a> </div>
                        </div>
                      </div>
                    <div class="page-content col-lg-8 col-md-8 col-sm-12 col-xs-12">
                      @yield('content')
                    </div>
            </div>
        </div>
    </div>
</div>
<!-- Main End --> 

resources/views/flash.blade.php
@if (session('success'))
    <div class="alert alert-success" style="text-align: center;">{{ session('success') }}</div>
@endif

resources/views/listresources.blade.php
@include('_header')
<div class="wrapper">
    <!-- Side Menu Start -->
    <div id="overlay"></div>
    <div id="mobile-menu">
        <ul>
            <li>
                <div class="mm-search">
                    <form id="search" name="search">
                        <div class="input-group">
                            <input type="text" class="form-control simple" placeholder="Search ..." name="srch-term" id="srch-term">
                       <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="icon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </li>
            <li><a href="index.html">Home</a></li>
            <li class="active"><a href="/#courses">Courses</a>

            </li>

            <li><a href="{{route('events.index')}}">Events</a>

            </li>

            <li><a href="{{route('contact')}}">Contact</a>

            </li>

        </ul>
    </div>
    <!-- Side Menu End -->

    <!-- Sub Header Start -->
    <div class="page-section" style="background:#ebebeb; padding:50px 0 35px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="cs-page-title">
                        <h1>Resources</h1>
                        <p style="color:#aaa;">A selection of resources of general interest</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Sub Header End -->
    <br><br>

    <!-- Main Start -->
    <div class="main-section">
      <div class="page-section">
        <div class="container">
          <div class="row">
            <div class="page-content col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <div class="row" id="book-list">
                <!-- <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="cs-sorting-list">
                    <div class="cs-left-side">
                      <div class="cs-select-holder">
                          <input type="text" class="search" placeholder="Search" />
                      </div>
                  </div>
                </div> -->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <ul class="cs-courses courses-simple" style="margin-bottom: 0px">
                      <li class="cs-header">
                        <div class="cs-courses-name"><span>Resource name</span></div>
                        <div class="cs-courses-date"><span>Type</span></div>

                        <div class="cs-price"><span>Download</span></div>
                      </li>
                    </ul>
                    <ul class="cs-courses courses-simple list" id="list">


                        @foreach($resources as $resource)

                            <li>
                                <div class="cs-courses-name filename"><h6> {{ $resource->title}} </h6></div>
                                <div class="cs-courses-date"><span class="post-date" style="text-transform: uppercase;"> {{File::extension($resource->link)}}</span></div>

                                <div class="cs-courses-level"><a href="/{{$resource->link}}"><span class="it" style="margin-left: 50px;cursor: pointer;"><i class="fa fa-download"></i></span></a></div>
                            </li>
                        @endforeach


                    </ul>


                    <form style="display: none" method="post" id="document-form" action="api/download-resources">
                        <input type="text" name="file_names" id="file-name-field">
                    </form>
                    <form style="display: none" method="post" id="single-document-form" action="api/download-single-file">
                        <input type="text" name="file_name" id="single-file-name-field">
                    </form>
                    <button id="download-btn" class="btn btn-primary btn-lg" style="display: none">Download Selected Items</button>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

</div>


{{--  Footer start  --}}
<footer id="footer" style="position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    text-align: center;">


    <div class="cs-copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="copyright-text">
                        <p>© {{ Carbon\Carbon::now()->year }} Wizer Consulting All Rights Reserved.</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="cs-social-media">
                        <ul>
                            <li><a href="index.html#"><i class="icon-facebook2"></i></a></li>
                            <li><a href="index.html#"><i class="icon-twitter2"></i></a></li>
                            <li><a href="index.html#"><i class="icon-instagram2"></i></a></li>
                            <li><a href="index.html#"><i class="icon-youtube3"></i></a></li>
                            <li><a href="index.html#"><i class="icon-linkedin22"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>


</footer>

{{-- Footer end --}}

resources/views/test.blade.php
@extends('_main')

@section('content')

<div id="app">
    <example-component></example-component>
</div>
    
@endsection

    