routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Category;
use App\Course;
use App\Filter;
use App\User;
use App\Training;
use App\Comment;
use App\Organization;


Route::get('/', function () {


	$categories = Category::all();
	$courses = Course::all();
	$comments = Comment::all();
	$filters = Filter::all();
	//$trainings = Training::all();
	$trainings = Training::orderby('start_date', 'asc')->get();
	$organizations = Organization::all();
	$users = User::all();

	//Put homepage path to session, to be accessed from logincontroller
	session(['path' => '/']);

    return view('welcome')->with('categories', $categories)
    					  ->with('courses', $courses)
    					  ->with('filters', $filters)
    					  ->with('comments', $comments)
    					  ->with('trainings', $trainings)
    					  ->with('organizations', $organizations)
    					  ->with('users', $users);
})->name('/');

Route::get('/events/results', function(){

	$events = Training::where('title', 'like', '%' . request('query') . '%');
	$trainings = Training::all();

	return view('events.results')->with('events', $events)
						  		->with('title', 'Search results : ' . request('query'))
								  ->with('query', request('query'))
								  ->with('trainings', $trainings);

});

Route::post('/events/materials', 'EventController@materials');

Route::get('/test', function() {


	return view('test');


});



Auth::routes();

Route::post('/home', 'HomeController@store')->name('home.store');



Route::get('contact', 'EventController@contact')->name('contact'); //Consider a dedicated controller here

Route::resource('events', 'EventController');
Route::resource('courses', 'CurriculumController');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/upcoming', 'HomeController@upcoming')->name('upcoming');
Route::get('/setting', 'HomeController@setting')->name('setting');



Route::post('/setting', 'HomeController@updateSetting')->name('update-setting');

Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay');

Route::get('/purchase', function(){



	return view('purchase');

});


Route::post('delegates/add', 'DelegateController@add');

Route::post('delegates/persist', 'DelegateController@persist');

Route::post('delegates/proof', 'DelegateController@payment_proof')->name('delegates.proof');

Route::post('delegates/narration', 'DelegateController@narration')->name('narration.proof');

Route::get('delegates/transactions/update', 'DelegateController@edit_transactions');

Route::post('delegates/transactions/update', 'DelegateController@update_transactions')->name('transactions.update');

Route::post('upload', 'HomeController@upload');

Route::post('/purchase', 'DelegateController@purchase')->name('purchase');

//note to self: consider putting path session here as well just like in home

Route::post('delegates/create', 'DelegateController@create');

Route::resource('delegates', 'DelegateController');

Route::get('/resources', 'ListResourcesController@index');


Route::prefix('admin')->middleware('role:superadministrator|administrator')->group(function () {

	Route::get('/', 'AdminController@index');

	Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');

	Route::resource('categories', 'CategoryController');

	Route::resource('courses', 'CourseController');

	Route::resource('filters', 'FilterController');

	Route::resource('trainings', 'TrainingController');

	Route::resource('instructors', 'InstructorController');

	Route::resource('organizations', 'OrganizationController');

	Route::resource('comments', 'CommentController');

	Route::resource('users', 'UserController');

    Route::resource('materials', 'MaterialController');

    Route::resource('resources', 'ResourceController');

	Route::resource('logos', 'LogoController');

	Route::resource('transactions', 'TransactionController');

	Route::resource('/permissions', 'PermissionController', ['except' => 'destroy']);
    Route::resource('/roles', 'RoleController', ['except' => 'destroy']);

});

app/Instructor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Instructor extends Model
{
    protected $fillable = [
	'first_name', 'last_name', 'email', 'about'
	];

	public function trainings()
    {
        return $this->belongsToMany('App\Training', 'instructor_training');
    }
}

app/Http/Controllers/InstructorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Instructor;
use App\Training;
use Session;

class InstructorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $instructors = Instructor::orderby('id', 'desc')->paginate(5); 

        return view('instructors.index')->with('instructors', $instructors);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $trainings = Training::all();
        
        return view('instructors.create', compact('trainings'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'about' => 'max:500',
            'avatar' => 'image',
            'email' => 'required|string|email|max:255|unique:instructors',
            
            ]);

        $instructor = new Instructor();

        
        $instructor->first_name = $request->get('first_name');
        $instructor->last_name = $request->get('last_name');
        $instructor->avatar = $request->get('avatar');
        $instructor->email = $request->get('email');
        $instructor->about = $request->get('about');
        $instructor->title = $request->get('title');

        if($request->hasFile('avatar'))
        {
            
            $avatar = $request->avatar;
            
            $avatar_new_name = $instructor->first_name.$instructor->last_name.".".$avatar->getClientOriginalExtension();
            $avatar->move('assets/uploads/instructors', $avatar_new_name);
            
            $instructor->avatar = 'assets/uploads/instructors/' . $avatar_new_name;
        }
        else
        {
            $instructor->avatar = 'assets/uploads/instructors/1.png';
        }

        $instructor->save();

        $instructor->trainings()->sync($request->trainings);

        Session::flash('success', 'Successfully created a new instructor');
        return redirect()->route('instructors.index');
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $instructor = Instructor::findOrFail($id);
        return view('instructors.show', compact('instructor'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $instructor = Instructor::findOrFail($id);
        $trainings = Training::all();
        return view('instructors.edit', compact('instructor', 'trainings'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $instructor = Instructor::find($id);

        $this->validate($request, [
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'about' => 'max:500',
            'avatar' => 'image',
            'email' => 'required|string|email|max:255|unique:instructors,email,'.$id,
            
            ]);

        $instructor->first_name = $request->get('first_name');
        $instructor->last_name = $request->get('last_name');
        $instructor->title = $request->get('title');
        $instructor->about = $request->get('about');
        $instructor->email = $request->get('email');

        if($request->hasFile('avatar'))
        {
            
            $avatar = $request->avatar;
            
            $avatar_new_name = $instructor->first_name.$instructor->last_name.".".$avatar->getClientOriginalExtension();
            $avatar->move('assets/uploads/instructors', $avatar_new_name);
            
            $instructor->avatar = 'assets/uploads/instructors/' . $avatar_new_name;
        }

        $instructor->save();

        $c = $request->trainings;
        

        if (isset($c)) {        
            $instructor->trainings()->sync($c);  
        }        
        else {
            $instructor->trainings()->detach(); //If no training is selected remove exisiting training
        }

        Session::flash('success', 'Successfully updated the instructor');
        return redirect()->route('instructors.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $instructor = Instructor::find($id);
        $instructor->trainings()->detach();

        $instructor->delete();
        return redirect()->route('instructors.index')->with('success','The Instructor has been  deleted');
    }
}

resources/views/instructors/create.blade.php
@extends('_admin')

@section('title', "|Add Instructor")
@section('content')
<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading main-color-bg">
			<h3 class="panel-title">Add Instructor</h3>
		</div>

		<div class="panel-body">
		  <div class="row">
		    <div class="col-md-12">

		      <form action="{{route('instructors.store')}}" enctype="multipart/form-data" method="post">
		      	@csrf
        		
		        <div class="form-group">
		          <label>First Name</label>
		          <input name="first_name" type="text" class="form-control">
		        </div>

		        <div class="form-group">
		          <label>Last Name</label>
		          <input name="last_name" type="text" class="form-control">
		        </div>

		        <div class="form-group">
		          <label>Title</label>
		          <input name="title" type="text" class="form-control">
		        </div>

		        <div class="form-group">
                    <label for="name">Upload image</label>
                    <input type="file" name="avatar"  class="form-control">
                </div>

		        <div class="form-group">
		          <label>Email</label>
		          <input name="email" type="email" class="form-control">
		        </div>

		        <div class="form-group">
		          <label>About</label>
		          <textarea class="form-control" rows="2" cols="111" name="about"></textarea>
		        </div>

		        
		        <div class="row">
		        	

					<div class="col-md-12">
						
						<div class="col-md-6">

							<div class="form-group">
			        			<label>Training</label>
				        		@foreach($trainings as $training)
							        <div class="checkbox">
							        	
					        			<label><input type="checkbox" name="trainings[]" value='{{ $training->id }}'>{{ $training->title }}</label><br>
					  					
									</div>
								@endforeach
							</div>
						</div>
						
						
					</div>				

				</div>
	
		        <button type="submit" class="btn btn-default btn-block" id="btnEmpty">Save</button>
		      </form>

		    </div>
		  </div>

		</div>
	</div>
	
</div>


@endsection

resources/views/instructors/edit.blade.php
@extends('_admin')

@section('title', "|Edit Instructor")
@section('content')
<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading main-color-bg">
			<h3 class="panel-title">Edit Instructor</h3>
		</div>

		<div class="panel-body">
		  <div class="row">
		    <div class="col-md-12">

		      <form action="{{action('InstructorController@update', $instructor['id'])}}" enctype="multipart/form-data" method="post" data-smk-icon="glyphicon-remove-sign" class="well">
		      	@csrf
        		<input name="_method" type="hidden" value="PATCH">

        		<div class="form-group">
		          <label>First Name</label>
		          <input type="text" name="first_name" value="{{$instructor->first_name}}" class="form-control" required>
		        </div>

		        <div class="form-group">
		          <label>Last Name</label>
		          <input type="text" name="last_name" value="{{$instructor->last_name}}" class="form-control" required>
		        </div>

		        <div class="form-group">
		          <label>Title</label>
		          <input type="test" name="title" value="{{$instructor->title}}" class="form-control" required>
		        </div>

		        <div class="form-group">
                    <label for="name">Upload new image</label>
                    <input type="file" name="avatar" class="form-control">
                </div>

		        <div class="form-group">
		          <label>Email</label>
		          <input type="email" name="email" value="{{$instructor->email}}" class="form-control" required>
		        </div>

		        <div class="form-group">
		          <label>About</label>
		          <textarea class="form-control" rows="2" cols="111" name="about">{{$instructor->about}}</textarea>
		        </div>

		       

		        <div class="row">
		        	
					<div class="col-md-12">
						<div class="col-md-6">
							<div class="form-group">
		        			<label>Trainings</label>
		        	
				        	@foreach($trainings as $training)
				        		<div class="checkbox">
							    	
							        <label>
							        	<input type="checkbox" name="trainings[]" value='{{ $training->id }}'
							        	@if(count($instructor->trainings->where('id', $training->id)) )
							            	checked="1"
							        	@endif
							        	>
							        	{{ $training->title }}
							        </label>
							        <br>
						    	</div>
						 	@endforeach
						</div>
					</div>

						

					</div>
				</div>

				


		        <button type="submit" class="btn btn-default btn-block" id="btnEmpty">Save Changes</button>
		      </form>

		    </div>
		  </div>

		</div>
	</div>
	
</div>


@endsection

resources/views/instructors/index.blade.php
@extends('_admin')
@section('content')
@section('title', "|Instructors" )
<div class="col-md-9">
	<div class="panel panel-default">
      <div class="panel-heading main-color-bg">
        <h3 class="panel-title">Instructors</h3>
      </div>
      <div class="panel-body">
      	<button type="button" class="btn btn-default pull-right"><a href="{{route('instructors.create')}}">New Instructor</a></button>
      	<table class="table table-striped" id="table">
		    <thead>
		      <tr>
		      	<th>Image</th>
		        <th>First Name</th>
		        <th>Last Name</th>
		        <th>Email</th>


		        <th>Trainings</th>


                <th></th>
                <th></th>
                <th></th>
		      </tr>
		    </thead>
		    <tbody>
		    	@foreach ($instructors as $instructor)

			      <tr>
			      	<td><img src="{{ asset($instructor->avatar) }}" alt="" style="60px" height="60px" style="border-radius: 50%"></td>
			        <td>{{str_limit($instructor->first_name, 10)}}</td>
			        <td>{{str_limit($instructor->last_name, 10)}}</td>
			        <td>{{$instructor->email}}</td>




			        <td>{{str_limit($instructor->trainings->pluck('title')->implode(', '), 10)}}</td>

			        <td>
			        	<a href="{{ route('instructors.show', $instructor->id) }}">
			        	<i class="glyphicon glyphicon-folder-open" ></i></a>
			        </td>

			        <td>
			        	<a href="{{ route('instructors.edit', $instructor->id) }}">
			        	<i class="glyphicon glyphicon-edit" ></i></a>
			        </td>
			        <td>

			          	<form class="delete" action="{{action('InstructorController@destroy', $instructor['id'])}}" method="POST">
	        				<input type="hidden" name="_method" value="DELETE">
	        				@csrf

	        				<button type="submit" class="delete" style="background-color: transparent; border:transparent;">
        						<i class="glyphicon glyphicon-trash"></i>
        					</button>
    					</form>
			        </td>


			      </tr>
			    @endforeach
		    </tbody>
		</table>
		<div class="text-center">{!! $instructors->links() !!}</div>
     </div>

</div>


@endsection

resources/views/instructors/show.blade.php
@extends('_admin')
@section('content')
@section('title', "|Instructor" )

<div class="col-md-9">
	<div class="panel panel-default">
      <div class="panel-heading main-color-bg">
        <h3 class="panel-title">Instructor</h3>
      </div>
      <div class="panel-body">
      	<button type="button" class="btn btn-default pull-right"><a href="{{route('instructors.edit', $instructor->id)}}">Edit Instructor</a></button>

      	<div class="col-md-12">
      		<div class="col-md-4">

      			<h5><strong>First Name</strong></h5>
      			{{$instructor->first_name}}
      			
      		</div>

      		<div class="col-md-4">

      			<h5><strong>Last Name</strong></h5>
      			{{$instructor->last_name}}
      			
      		</div>

      		<div class="col-md-4">

      			<h5><strong>Email</strong></h5>
      			{{$instructor->email}}
      			
      		</div>

      		

      		
      	</div>
      	
      	<!-- <div class="container">
      		<div class="row">
	      		<div class="col-md-12">
	      		
	      			<h5><strong>Trainings</strong></h5>
	      			{{$instructor->trainings->pluck('title')->implode(', ')}}
	      		
	      		</div>
      		</div>
      	</div> -->

      	
      		<div class="row">
	      		<div class="col-md-12">
			
					<table class="table">
					<thead>
					  <tr>
					    <th><h5 class="text-center"><strong>Trainings</strong></h5>
					    </th>
					    
					  </tr>
					</thead>
					<tbody>
						@foreach($instructor->trainings as $training)
							<tr>
							<td>{{$training->title}}</td>

							</tr>
						@endforeach
						
					</tbody>
					</table>
				</div>
			</div>
		
      	
      	
      	
		
    </div>

</div>
@endsection