routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Category;
use App\Course;
use App\Filter;
use App\User;
use App\Training;
use App\Comment;
use App\Organization;


Route::get('/', function () {


	$categories = Category::all();
	$courses = Course::all();
	$comments = Comment::all();
	$filters = Filter::all();
	//$trainings = Training::all();
	$trainings = Training::orderby('start_date', 'asc')->get();
	$organizations = Organization::all();
	$users = User::all();

	//Put homepage path to session, to be accessed from logincontroller
	session(['path' => '/']);

    return view('welcome')->with('categories', $categories)
    					  ->with('courses', $courses)
    					  ->with('filters', $filters)
    					  ->with('comments', $comments)
    					  ->with('trainings', $trainings)
    					  ->with('organizations', $organizations)
    					  ->with('users', $users);
})->name('/');

Route::get('/events/results', function(){

	$events = Training::where('title', 'like', '%' . request('query') . '%');
	$trainings = Training::all();

	return view('events.results')->with('events', $events)
						  		->with('title', 'Search results : ' . request('query'))
								  ->with('query', request('query'))
								  ->with('trainings', $trainings);

});

Route::post('/events/materials', 'EventController@materials');

Route::get('/test', function() {


	return view('test');


});



Auth::routes();

Route::post('/home', 'HomeController@store')->name('home.store');



Route::get('contact', 'EventController@contact')->name('contact'); //Consider a dedicated controller here

Route::resource('events', 'EventController');
Route::resource('courses', 'CurriculumController');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/upcoming', 'HomeController@upcoming')->name('upcoming');
Route::get('/setting', 'HomeController@setting')->name('setting');



Route::post('/setting', 'HomeController@updateSetting')->name('update-setting');

Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay');

Route::get('/purchase', function(){



	return view('purchase');

});


Route::post('delegates/add', 'DelegateController@add');

Route::post('delegates/persist', 'DelegateController@persist');

Route::post('delegates/proof', 'DelegateController@payment_proof')->name('delegates.proof');

Route::post('delegates/narration', 'DelegateController@narration')->name('narration.proof');

Route::get('delegates/transactions/update', 'DelegateController@edit_transactions');

Route::post('delegates/transactions/update', 'DelegateController@update_transactions')->name('transactions.update');

Route::post('upload', 'HomeController@upload');

Route::post('/purchase', 'DelegateController@purchase')->name('purchase');

//note to self: consider putting path session here as well just like in home

Route::post('delegates/create', 'DelegateController@create');

Route::resource('delegates', 'DelegateController');

Route::get('/resources', 'ListResourcesController@index');


Route::prefix('admin')->middleware('role:superadministrator|administrator')->group(function () {

	Route::get('/', 'AdminController@index');

	Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');

	Route::resource('categories', 'CategoryController');

	Route::resource('courses', 'CourseController');

	Route::resource('filters', 'FilterController');

	Route::resource('trainings', 'TrainingController');

	Route::resource('instructors', 'InstructorController');

	Route::resource('organizations', 'OrganizationController');

	Route::resource('comments', 'CommentController');

	Route::resource('users', 'UserController');

    Route::resource('materials', 'MaterialController');

    Route::resource('resources', 'ResourceController');

	Route::resource('logos', 'LogoController');

	Route::resource('transactions', 'TransactionController');

	Route::resource('/permissions', 'PermissionController', ['except' => 'destroy']);
    Route::resource('/roles', 'RoleController', ['except' => 'destroy']);

});

app/Training.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Training extends Model
{
    
    protected $fillable = [
		'title', 'venue', 'description', 'cost', 'start_date', 'end_date'
	];

    public function courses()
    {
    	return $this->belongsToMany('App\Course', 'course_training');
    }

    public function organizations()
    {
    	return $this->belongsToMany('App\Organization', 'organization_training', 'training_id', 'organization_id');
    }

    public function users()
    {
        return $this->belongsToMany('App\User', 'training_user', 'training_id', 'user_id');
    }

    public function instructors()
    {
        return $this->belongsToMany('App\Instructor', 'instructor_training', 'training_id', 'instructor_id');
    }

    public function transactions()
    {
        return $this->hasMany('App\Transaction');
    }
}

app/Http/Controllers/TrainingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Training;
use App\Course;
use App\Instructor;
use Session;
use Purifier;

class TrainingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $trainings = Training::all();
        return view('trainings.index')->with('trainings', $trainings);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        $courses = Course::all();
        $instructors = Instructor::all();
        return view('trainings.create', compact('courses', 'instructors'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $this->validate($request, [
            'title'=>'required|max:80',
            
            'image'=>'required|image',
            'venue'=>'required',
            
            'outcome'=>'required|max:820',
            'course_delivery'=>'required|max:800',
            'who_should_attend'=>'required|max:800',
            'cost'=>'required',
            'start_date'=>'required|date',
            'end_date' =>'required|date|after:start_date'
            ]);

        $training = new Training();
        
        $training->title = $request->title;
        $training->venue = Purifier::clean($request->venue);
        $training->cost = $request->cost;
        $training->description = Purifier::clean($request->description);
        $training->outcome = Purifier::clean($request->outcome);
        $training->course_delivery = Purifier::clean($request->course_delivery);
        $training->who_should_attend = Purifier::clean($request->who_should_attend);
        $training->start_date = date("Y-m-d H:i:s", strtotime($request->start_date));
        $training->end_date = date("Y-m-d H:i:s", strtotime($request->end_date));

        if ($request->image) {
            
            $image = $request->image;
            $image_new_name = time() . $image->getClientOriginalName();
        
            $image->move('assets/uploads/trainings', $image_new_name);
            
            $training->image = 'assets/uploads/trainings/' . $image_new_name;
        }
        
       
        
        $training->save();

        $training->courses()->sync($request->courses);

        $training->instructors()->sync($request->instructors);


        return redirect()->route('trainings.index')->with('success', 'A new training has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('trainings.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $training = Training::findOrFail($id);
        $courses = Course::all();
        $instructors = Instructor::all();
        

        return view('trainings.edit', compact('training', 'courses', 'instructors'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $training = Training::find($id);
        
         $this->validate($request, [
            'title'=>'required|max:80',
            'image'=>'image',
            //'image'=>'image',
            'venue'=>'required',
            //'description'=>'required',
            'outcome'=>'required|max:820',
            'course_delivery'=>'required|max:800',
            'who_should_attend'=>'required|max:800',
            'cost'=>'required',
            'start_date'=>'required|date',
            'end_date' =>'required|date|after:start_date'
            ]);

        $training->title = $request->title;
        $training->venue = Purifier::clean($request->venue);
        $training->cost = $request->cost;
        $training->description = Purifier::clean($request->description);
        $training->outcome = Purifier::clean($request->outcome);
        $training->course_delivery = Purifier::clean($request->course_delivery);
        $training->who_should_attend = Purifier::clean($request->who_should_attend);        
        $training->start_date = date("Y-m-d H:i:s", strtotime($request->start_date));
        $training->end_date = date("Y-m-d H:i:s", strtotime($request->end_date));

        if ($request->image)
        {
            $image = $request->image;
            $image_new_name = time() . $image->getClientOriginalName();
        
            $image->move('assets/uploads/trainings', $image_new_name);
            
            $training->image = 'assets/uploads/trainings/' . $image_new_name;
        }
        
        $training->save();

        $c = $request->courses;

        if (isset($c)) {        
            $training->courses()->sync($c);  
        }        
        else {
            $training->courses()->detach(); 
        }

        $i = $request->instructors;

        if (isset($i)) {        
            $training->instructors()->sync($i);  
        }        
        else {
            $training->instructors()->detach(); 
        }

       
    
        Session::flash('success', 'Successfully updated the training');
        return redirect()->route('trainings.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $training = Training::find($id);
        $training->courses()->detach();
        $training->instructors()->detach();
        $training->users()->detach();
        $training->organizations()->detach();
        
        $training->delete();
        return redirect()->route('trainings.index')->with('success','Training has been deleted');
    }
}

resources/views/trainings/create.blade.php
@extends('_admin')

@section('title', "|Create Training")
@section('content')
<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading main-color-bg">
			<h3 class="panel-title">Create Training</h3>
		</div>

		<div class="panel-body">
		  <div class="row">
		    <div class="col-md-12">

		      <form action="{{route('trainings.store')}}" enctype="multipart/form-data" method="post">
		      	@csrf

		      	<div class="form-group">
		          <label>Title</label>
		          <input type="text" name="title" class="form-control" value="{{$training->title or old('title') }}">
		        </div>

		        <div class="form-group">
                    <label for="name">Featured Image</label>
                    <input type="file" name="image"  class="form-control" >
                </div>

		        <div class="form-group">
		          <label>Venue</label>
		          <textarea class="form-control" rows="2" cols="111" name="venue">{{$training->venue or old('venue') }}</textarea>		          
		        </div>

		        <div class="form-group">
		          <label>Description</label>
		          <textarea class="form-control" rows="2" cols="111" name="description">{{$training->description or old('description') }}</textarea>		          
		        </div>

		        <div class="form-group">
		          <label>Outcome</label>
		          <textarea class="form-control" rows="2" cols="111" name="outcome">{{$training->outcome or old('outcome') }}</textarea>		          
		        </div>

		        <div class="form-group">
		          <label>Course Delivery</label>
		          <textarea class="form-control" rows="2" cols="111" name="course_delivery">{{$training->course_delivery or old('course_delivery')}}</textarea>		          
		        </div>

		        <div class="form-group">
		          <label>Who Should Attend</label>
		          <textarea class="form-control" rows="2" cols="111" name="who_should_attend">{{$training->who_should_attend or old('who_should_attend') }}</textarea>		          
		        </div>

		        <div class="form-group">
		          <label>Cost Per Participant(N)</label>
		          <input type="number" class="form-control" name="cost" placeholder="1.0" step="0.01" min="0" max="10000000" value="{{$training->cost or old('cost') }}">
		          
		        </div>

        		
		        <div class="form-group">
		          <label>Start Date</label>
		          <div class='input-group date' id='datetimepicker1'>
		          	<input type="text" name="start_date" class="form-control" value="{{$training->start_date or old('start_date') }}" placeholder="MM/DD/YYY" required >
		          	<span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
		      	  </div>
		        </div>

		        <div class="form-group">
		          <label>End Date</label>
		          <div class='input-group date' id='datetimepicker2'>
		          	<input type="text" name="end_date" class="form-control" value="{{$training->end_date or old('end_date') }}" placeholder="MM/DD/YYY" required>
		          	<span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
		      	  </div>
		        </div>

		        <div class="row">
		        	<div class="col-md-12">
		        		<div class="col-md-6">
		        			<div class="form-group">
		        			<label>Courses</label>
		        			@foreach($courses as $course)
					        <div class="checkbox">
					        	
			        			<label><input type="checkbox" name="courses[]" value='{{ $course->id }}'>{{ $course->title }}</label><br>
			  					
							</div>
							@endforeach
							</div>
		        		
		        		</div>

		        		<div class="col-md-6">
		        			<div class="form-group">
		        			<label>Instructors</label>
		        			@foreach($instructors as $instructor)
					        <div class="checkbox">
					        	
			        			<label><input type="checkbox" name="instructors[]" value='{{ $instructor->id }}'>{{ $instructor->first_name }} {{$instructor->last_name}}</label><br>
			  					
							</div>
							@endforeach
							</div>
		        		
		        		</div>
		        		
		        	</div>
		        </div>
		        
		        <button type="submit" class="btn btn-default btn-block" id="btnEmpty">Save</button>
		      </form>

		    </div>
		  </div>

		</div>
	</div>
	
</div>


@endsection

resources/views/trainings/edit.blade.php
@extends('_admin')

@section('title', "|Edit Training")
@section('content')

<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading main-color-bg">
			<h3 class="panel-title">Edit Training</h3>
		</div>

		<div class="panel-body">
		  <div class="row">
		    <div class="col-md-12">

		      <form action="{{action('TrainingController@update', $training['id'])}}" enctype="multipart/form-data" method="post" data-smk-icon="glyphicon-remove-sign" class="well">
		      	@csrf
        		<input name="_method" type="hidden" value="PATCH">

        		<div class="form-group">
		          <label>Title</label>
		          <input class="form-control" type="text" name="title" value="{{ $training->title }}" class="form-control" required>
		        </div>

		        <div class="form-group">
                    <label for="name">Featured Image</label>
                    <input type="file" name="image"  class="form-control" >
                </div>

		        <!-- <div class="form-group">
		          <label>Venue</label>
		          <input class="form-control" type="text" name="venue" value="{{ $training->venue }}" class="form-control" required>
		        </div> --> 

		        <div class="form-group">
		          <label>Venue</label>
		          <textarea class="form-control" rows="2" cols="106" name="venue">{{$training->venue}}</textarea>		          
		        </div>

		        <div class="form-group">
		          <label>Description</label>
		          <textarea class="form-control" rows="2" cols="106" name="description">{{$training->description}}</textarea>		          
		        </div>

		        <div class="form-group">
		          <label>Outcome</label>
		          <textarea class="form-control" rows="2" cols="111" name="outcome">{{$training->outcome}}</textarea>		          
		        </div>

		        <div class="form-group">
		          <label>Course Delivery</label>
		          <textarea class="form-control" rows="2" cols="111" name="course_delivery">{{$training->course_delivery}}</textarea>		          
		        </div>

		        <div class="form-group">
		          <label>Who Should Attend</label>
		          <textarea class="form-control" rows="2" cols="111" name="who_should_attend">{{$training->who_should_attend}}</textarea>		          
		        </div>

		        <div class="form-group">
		          <label>Cost Per Participant</label>
		          <input class="form-control" type="number" name="cost" step="0.01" min="0" max="10000000" value="{{$training->cost}}">
		          
		        </div>

        		

		        <div class="form-group">
		          <label>Start Date</label>
		          <div class='input-group date' id='datetimepicker1'>
		          	<input type="text" name="start_date" class="form-control" value="{{$training->start_date or old('start_date') }}" required>
		          	<span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
		      	  </div>
		        </div>

		        <div class="form-group">
		          <label>End Date</label>
		          <div class='input-group date' id='datetimepicker2'>
		          	<input type="text" name="end_date" class="form-control" value="{{$training->end_date or old('end_date') }}"required>
		          	<span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
		      	  </div>
		        </div>

		        <div class="row">
		        	<div class="col-md-12">

		        		<div class="col-md-6">
		        			<div class="form-group">
		        				<label>Courses</label>
		        	
					        	@foreach($courses as $course)
					        		<div class="checkbox">
								    	

								        <label>
								        	<input type="checkbox" name="courses[]" value='{{ $course->id }}'
								        	@if( count($training->courses->where('id', $course->id)) )
								            	checked="1"
								        	@endif
								        	>
								        	{{ $course->title }}
								        </label>
								        <br>
							    	</div>
							 	@endforeach
							</div>
		        		</div>

		        		<div class="col-md-6">
		        			<div class="form-group">
		        				<label>Instructors</label>
		        	
					        	@foreach($instructors as $instructor)
					        		<div class="checkbox">
								    	

								        <label>
								        	<input type="checkbox" name="instructors[]" value='{{ $instructor->id }}'
								        	@if( count($training->instructors->where('id', $instructor->id)) )
								            	checked="1"
								        	@endif
								        	>
								        	{{ $instructor->first_name }} {{ $instructor->last_name }}
								        </label>
								        <br>
							    	</div>
							 	@endforeach
							</div>
		        		</div>

		        	</div>
		        </div>
				


		        <button type="submit" class="btn btn-default btn-block" id="btnEmpty">Save Changes</button>
		      </form>

		    </div>
		  </div>

		</div>
	</div>
	
</div>


@endsection

resources/views/trainings/index.blade.php
@extends('_admin')
@section('content')
@section('title', "|Training" )
<div class="col-md-9">
	<div class="panel panel-default">
      <div class="panel-heading main-color-bg">
        <h3 class="panel-title">All Training <span class="pull-right"><a href="{{route('trainings.create')}}" style="color: white;">Add Training</a></span></h3>

      </div>
      <div class="panel-body">

      	<br>
      	<table class="table table-striped" id="table">
      		<!-- <button type="button" class="btn btn-default pull-right"><a href="{{route('trainings.create')}}">New Training</a></button> -->
		    <thead>
		      <tr>
		        <th>Title</th>
		        <th>Venue</th>

		        <th>Cost (&#8358;)</th>
		        <!-- <th>Courses</th> -->
		        <th>Start Date</th>
		        <th>End Date</th>

		        <th></th>
		        <th></th>
		      </tr>
		    </thead>
		    <tbody>
		    	@foreach ($trainings as $training)

			      <tr>
			      	<td>{{str_limit($training->title), 10}}</td>
			      	<td>{{strip_tags(str_limit($training->venue)), 50}}</td>

			      	<td>{{number_format($training->cost)}}</td>
			      	<!-- <td>{{str_limit($training->courses()->pluck('title')->implode(', '), 50)}}</td> -->
			        <td>{{ \Carbon\Carbon::parse($training->start_date)->format('d M Y')}}</td>
			        <td>{{ \Carbon\Carbon::parse($training->end_date)->format('d M Y')}}</td>

			        <td>
			        	<a href="{{ route('trainings.edit', $training->id) }}">
			        	<i class="glyphicon glyphicon-edit" ></i></a>


			        </td>
			        <td>

			        	<form class="delete" action="{{action('TrainingController@destroy', $training['id'])}}" method="POST">
	        				<input type="hidden" name="_method" value="DELETE">
	        				@csrf

	        				<button type="submit" class="delete" style="background-color: transparent; border:transparent;">
        						<i class="glyphicon glyphicon-trash"></i>
        					</button>
    					</form>

			        </td>


			      </tr>
			    @endforeach
		    </tbody>
		</table>
		{{--  <div class="text-center">{!! $trainings->links() !!}</div>  --}}
      </div>

	</div>

</div>


@endsection