routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Category;
use App\Course;
use App\Filter;
use App\User;
use App\Training;
use App\Comment;
use App\Organization;


Route::get('/', function () {


	$categories = Category::all();
	$courses = Course::all();
	$comments = Comment::all();
	$filters = Filter::all();
	//$trainings = Training::all();
	$trainings = Training::orderby('start_date', 'asc')->get();
	$organizations = Organization::all();
	$users = User::all();

	//Put homepage path to session, to be accessed from logincontroller
	session(['path' => '/']);

    return view('welcome')->with('categories', $categories)
    					  ->with('courses', $courses)
    					  ->with('filters', $filters)
    					  ->with('comments', $comments)
    					  ->with('trainings', $trainings)
    					  ->with('organizations', $organizations)
    					  ->with('users', $users);
})->name('/');

Route::get('/events/results', function(){

	$events = Training::where('title', 'like', '%' . request('query') . '%');
	$trainings = Training::all();

	return view('events.results')->with('events', $events)
						  		->with('title', 'Search results : ' . request('query'))
								  ->with('query', request('query'))
								  ->with('trainings', $trainings);

});

Route::post('/events/materials', 'EventController@materials');

Route::get('/test', function() {


	return view('test');


});



Auth::routes();

Route::post('/home', 'HomeController@store')->name('home.store');



Route::get('contact', 'EventController@contact')->name('contact'); //Consider a dedicated controller here

Route::resource('events', 'EventController');
Route::resource('courses', 'CurriculumController');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/upcoming', 'HomeController@upcoming')->name('upcoming');
Route::get('/setting', 'HomeController@setting')->name('setting');



Route::post('/setting', 'HomeController@updateSetting')->name('update-setting');

Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay');

Route::get('/purchase', function(){



	return view('purchase');

});


Route::post('delegates/add', 'DelegateController@add');

Route::post('delegates/persist', 'DelegateController@persist');

Route::post('delegates/proof', 'DelegateController@payment_proof')->name('delegates.proof');

Route::post('delegates/narration', 'DelegateController@narration')->name('narration.proof');

Route::get('delegates/transactions/update', 'DelegateController@edit_transactions');

Route::post('delegates/transactions/update', 'DelegateController@update_transactions')->name('transactions.update');

Route::post('upload', 'HomeController@upload');

Route::post('/purchase', 'DelegateController@purchase')->name('purchase');

//note to self: consider putting path session here as well just like in home

Route::post('delegates/create', 'DelegateController@create');

Route::resource('delegates', 'DelegateController');

Route::get('/resources', 'ListResourcesController@index');


Route::prefix('admin')->middleware('role:superadministrator|administrator')->group(function () {

	Route::get('/', 'AdminController@index');

	Route::get('/dashboard', 'AdminController@dashboard')->name('admin.dashboard');

	Route::resource('categories', 'CategoryController');

	Route::resource('courses', 'CourseController');

	Route::resource('filters', 'FilterController');

	Route::resource('trainings', 'TrainingController');

	Route::resource('instructors', 'InstructorController');

	Route::resource('organizations', 'OrganizationController');

	Route::resource('comments', 'CommentController');

	Route::resource('users', 'UserController');

    Route::resource('materials', 'MaterialController');

    Route::resource('resources', 'ResourceController');

	Route::resource('logos', 'LogoController');

	Route::resource('transactions', 'TransactionController');

	Route::resource('/permissions', 'PermissionController', ['except' => 'destroy']);
    Route::resource('/roles', 'RoleController', ['except' => 'destroy']);

});

app/Organization.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Organization extends Model
{
    public function trainings()
    {
    	return $this->belongsToMany('App\Training', 'organization_training');
    }

    public function users()
    {
    	return $this->hasMany('App\User');
    }
}

app/Http/Controllers/OrganizationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Organization;
use App\Training;
use Session;

class OrganizationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $organizations = Organization::orderby('id', 'desc')->paginate(10);
        return view('organizations.index')->with('organizations', $organizations);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $trainings = Training::all();
        
        return view('organizations.create', compact('trainings'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'required',
            'code'=>'required|unique:organizations,code'
            
            ]);

        $organization = new Organization();
        $organization->name = $request->name;
        $organization->industry = $request->industry;
        $organization->code = $request->code;
        
        $organization->save();

        $organization->trainings()->sync($request->trainings);


        return redirect()->route('organizations.index')->with('success', 'A new Organization has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $organization = Organization::findOrFail($id);
        $trainings = Training::all();
        

        return view('organizations.edit', compact('organization', 'trainings'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $organization = Organization::find($id);
        
        $this->validate($request, [
            'name'=>'required'
            
            ]);

        $organization->name = $request->name;
        $organization->industry = $request->industry;
        $organization->code = $request->code;
        
        $organization->save();

        $c = $request->trainings;

        if (isset($c)) {        
            $organization->trainings()->sync($c);  
        }        
        else {
            $organization->trainings()->detach(); 
        }

       
    
        Session::flash('success', 'Successfully updated the Organization');
        return redirect()->route('organizations.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $organization = Organization::find($id);
        $organization->trainings()->detach();
        
        $organization->delete();
        return redirect()->route('organizations.index')->with('success','Organization has been  deleted');
    }
}

resources/views/organizations/create.blade.php
@extends('_admin')

@section('title', "|Add Organization")
@section('content')
<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading main-color-bg">
			<h3 class="panel-title">Add Organization</h3>
		</div>

		<div class="panel-body">
		  <div class="row">
		    <div class="col-md-12">

		      <form action="{{route('organizations.store')}}" method="post">
		      	@csrf

		        <div class="form-group">
		          <label>Name</label>
		          <input name="name" type="text" class="form-control" required>
						</div>

						<div class="form-group">
		          <label>Industry</label>
		          <input name="industry" type="text" class="form-control">
		        </div>

		        <div class="form-group">
		          <label>Code</label>
		          <input name="code" type="text" class="form-control" required>
		        </div>



		        <div class="form-group">
		        	<label>Training</label>
                    @foreach($trainings as $training)
                        @if(strtotime($training->end_date) - time() > 0 )
                            <div class="checkbox">

                                <label><input type="checkbox" name="trainings[]" value='{{ $training->id }}'>{{ $training->title }} <div>({{ \Carbon\Carbon::parse($training->start_date)->format('d M')}} - {{ \Carbon\Carbon::parse($training->end_date)->format('d M Y')}})</div></label><br>

                            </div>
                        @endif
					@endforeach
				</div>


		        <button type="submit" class="btn btn-default btn-block" id="btnEmpty">Save</button>
		      </form>

		    </div>
		  </div>

		</div>
	</div>

</div>


@endsection

resources/views/organizations/edit.blade.php
@extends('_admin')

@section('title', "|Edit Organization")
@section('content')
<div class="col-md-9">
	<div class="panel panel-default">
		<div class="panel-heading main-color-bg">
			<h3 class="panel-title">Edit Organization</h3>
		</div>

		<div class="panel-body">
		  <div class="row">
		    <div class="col-md-12">

		      <form action="{{action('OrganizationController@update', $organization['id'])}}" method="post" data-smk-icon="glyphicon-remove-sign" class="well">
		      	@csrf
        		<input name="_method" type="hidden" value="PATCH">

        		<div class="form-group">
		          <label>Name</label>
		          <input type="text" name="name" value="{{$organization->name}}" class="form-control" required>
						</div>
						
						<div class="form-group">
		          <label>Industry</label>
		          <input name="industry" type="text" value="{{$organization->industry}}" class="form-control">
		        </div>

		        
		        <div class="form-group">
		          <label>Code</label>
		          <input type="text" name="code" value="{{$organization->code}}" class="form-control" required>
		        </div>

		        

				<div class="form-group">
		        	<label>Trainings</label>
		        	
		        	@foreach($trainings as $training)
		        		<div class="checkbox">
					    	

					        <label>
					        	<input type="checkbox" name="trainings[]" value='{{ $training->id }}'
					        	@if( count($organization->trainings->where('id', $training->id)) )
					            	checked="1"
					        	@endif
					        	>
					        	{{ $training->title }}
					        </label>
					        <br>
				    	</div>
				 	@endforeach
				</div>


		        <button type="submit" class="btn btn-default btn-block" id="btnEmpty">Save Changes</button>
		      </form>

		    </div>
		  </div>

		</div>
	</div>
	
</div>


@endsection

resources/views/organizations/index.blade.php
@extends('_admin')
@section('content')
@section('title', "|Organizations" )
<div class="col-md-9">
	<div class="panel panel-default">
      <div class="panel-heading main-color-bg">
        <h3 class="panel-title">Organizations</h3>
      </div>
      <div class="panel-body">
      	<button type="button" class="btn btn-default pull-right"><a href="{{route('organizations.create')}}">New Organization</a></button>
      	<table class="table table-striped" id="table">
		    <thead>
		      <tr>
		        <th>Name</th>
		        <th>Code</th>
		        <th>Training</th>
		        <th></th>
		        <th></th>
		      </tr>
		    </thead>
		    <tbody>
		    	@foreach ($organizations as $organization)

			      <tr>
			        <td>{{$organization->name}}</td>
			        <td>{{$organization->code}}</td>
			        <td>{{str_limit($organization->trainings()->pluck('title')->implode(', '), 50)}}</td>

			        <td>
			        	<a href="{{ route('organizations.edit', $organization->id) }}">
			        	<i class="glyphicon glyphicon-edit" ></i></a>
			        </td>
			        <td>


			          	<form class="delete" action="{{action('OrganizationController@destroy', $organization['id'])}}" method="POST">
	        				<input type="hidden" name="_method" value="DELETE">
	        				@csrf

	        				<button type="submit" class="delete" style="background-color: transparent; border:transparent;">
        						<i class="glyphicon glyphicon-trash"></i>
        					</button>
    					</form>
			        </td>


			      </tr>
			    @endforeach
		    </tbody>
		</table>
		<div class="text-center">{!! $organizations->links() !!}</div>
      </div>

	</div>


@endsection